name: '✨ Feature Request'
description: '새로운 기능을 제안하려면 이 템플릿을 사용하세요.'
title: '[Feature] '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        ## 📄 Request

        <!-- ex) Header 구현, 특정 문제 발견, 의문점 -->
        ===
